name: CI
on:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  test:
    name: PHPUnit (PHP ${{ matrix.php-versions }}) (SF ${{ matrix.sf-version }}) (${{ matrix.composer }} dependencies)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sf-version: ["*"]
        php-versions: ['8.1', '8.2', '8.3', '8.4']
        composer: [ "lowest", "highest" ]
        include:
          - sf-version: "5.4.*"
            php-versions: '8.3'
            composer: 'highest'
          - sf-version: "6.4.*"
            php-versions: '8.3'
            composer: 'highest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-versions }}'
          extensions: mbstring,intl,mongodb
          tools: composer:v2,flex
      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.composer }}
        env:
          SYMFONY_REQUIRE: ${{ matrix.sf-version }}
      - name: PHPUnit
        run: composer test

  static-analysis:
    name: Static analysis (PHP ${{ matrix.php-versions }}) (${{ matrix.composer }} dependencies)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4']
        composer: ["lowest", "highest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-versions }}'
          extensions: mbstring,intl,mongodb
          tools: composer:v2
      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.composer }}
      - name: Install tools
        uses: ramsey/composer-install@v3
        with:
          working-directory: tools
      - name: PHPStan
        run: composer phpstan

  coding-style:
    name: Coding style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring,intl,mongodb
          tools: composer:v2
      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          working-directory: tools
      - name: PHP CS Fixer
        run: composer cs:lint
